# Generated by Django 5.0.6 on 2026-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pageview", "Page view"),
                            ("section", "Section reached"),
                            ("lang_switch", "Language switched"),
                            ("doc_open", "Document reader opened"),
                            ("doc_download", "PDF downloaded"),
                            ("clause_copy", "Model clause copied"),
                            ("inquiry_start", "Inquiry form started"),
                            ("inquiry_submit", "Inquiry submitted"),
                            ("cta", "Call to action clicked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                ("lang", models.CharField(blank=True, max_length=5)),
                ("path", models.CharField(blank=True, max_length=200)),
                ("visitor", models.CharField(blank=True, db_index=True, max_length=32)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("referrer_host", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "created_at"],
                        name="analytics_e_kind_544e39_idx",
                    )
                ],
            },
        ),
    ]
